name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install packages
        run: yarn
      - name: Run ESLint
        run: ./node_modules/.bin/eslint --ext .js,.vue ./
      - name: Run UATs
        run: yarn test:e2e:ci
        env:
          CYPRESS_baseUrl: http://localhost:8080/
          CYPRESS_ALGOLIA_APP_ID: ${{ secrets.CYPRESS_ALGOLIA_APP_ID }}
          CYPRESS_ALGOLIA_KEY: ${{ secrets.CYPRESS_ALGOLIA_KEY }}
