name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    env:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      # This allows self-signed ssl certs to work so UATs run against https
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - name: Checkout and Lint
        uses: actions/checkout@v1
      - name: Run ESLint
        run: yarn && yarn lint
      - name: Build app and Run UATs
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.json
          start: yarn start
          wait-on: 'https://localhost:8080'
          browser: chrome
          headless: true
      - name: Archive test screenshots
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: test/cypress/screenshots
        if: ${{ failure() }}
