name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    env:
      ALGOLIA_APP_ID: TF6EHQUG2K
      ALGOLIA_KEY: 3ab2216a85ee66f3ecd52c90c1f690fc
    steps:
      - name: Checkout and Lint
        uses: actions/checkout@v1
      - name: Run ESLint
        run: yarn && yarn lint
      - name: Build app and Run UATs
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.json
          start: yarn start
          wait-on: 'https://localhost:8080'
          browser: chrome
          headless: true
        env:
          # This allows self-signed ssl certs to work so UATs run against https
          NODE_TLS_REJECT_UNAUTHORIZED: 0
      - name: Archive test screenshots
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: test/cypress/screenshots
        if: ${{ failure() }}
